<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Ruchit" failures="1" tests="2" name="Test" time="66.284" errors="0" timestamp="2025-01-17T22:00:00 IST">
  <testcase classname="Page_Validation.HomeNav_Testing" name="NavValidation" time="16.744"/>
  <testcase classname="Page_Validation.KnowGoSectionLinks_Validation" name="SectionLinksValidation" time="33.729">
    <failure type="java.lang.AssertionError" message="expected [https://ada.com/covid/antiviral-treatment-criteria-questionnaire/] but found [https://www.covidknowandgo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://ada.com/covid/antiviral-treatment-criteria-questionnaire/] but found [https://www.covidknowandgo.com/]
at Page_Validation.KnowGoSectionLinks_Validation.SectionLinksValidation(KnowGoSectionLinks_Validation.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SectionLinksValidation -->
  <testcase classname="Base.Hooks" name="@BeforeTest SetUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest SetUp -->
  <testcase classname="Base.Hooks" name="@AfterTest TearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest TearDown -->
</testsuite> <!-- Test -->
